version: '3.7'
services:

  flask-app:
    image: flask-app
    build .
    ports:
      - target: 5000
        published: 80

  mysql:
    image: mysql:5.7
    environment:
       - MYSQL_ROOT_PASSWORD=password
       - MYSQL_DATABASE=blog-network

  jenkins:
     image: jenkins/jenkins:latest
     ports:
       - target: 8080
         published: 8080
     volumes:
       - type: volume
         source: jenkins-home
         target: "/var/jenkins_home"
       - type: bind
         source: "/var/run/docker.sock"
         target: "/var/run/docker.sock"

volumes:
 jenkins-home:
